### ISSUE TITLE
The device's advertising IDs are not transmitted or processed. 

### ISSUE THREAD

**Issue by trash-max** [Poing-Studios/godot-admob-android#192] opened 2023-10-11 12:51 UTC
### Godot version

4.1.2

### Plugin version

v3.0.0.0

### Phone information

Motorolla G13

### Issue description

Hi. Faced with a small problem. 
Play market reports an error, says that the AD_ID permission is not granted in the application that uses the plugin. (About API 33)
I added a com.google.android.gms.permission.AD_ID request to Godot, but the situation has not changed.  The device's advertising IDs are not transmitted or processed.
All my devices have been added to AdMob as test devices, everything worked fine in previous versions of the plugin.

### Steps to reproduce

1. Open Godot 4.1.2
2. Install and config plugin
3. Run test device
`/Android/Sdk/emulator/emulator -avd Nexus_5_API_33`
4. And see commercial ADs. :(

### Additional context

I can send some screenshots or logs, if need.

**Comment by gumaciel** [comment] 2023-10-12 02:02
Hi, strange because you don't need to do anything about it: https://support.google.com/googleplay/android-developer/answer/6048248

If your app uses these SDKs as dependencies, the AD_ID permission from the SDK’s library manifest will be merged with your app’s main manifest by default, even if you don’t explicitly declare the permission in your app’s main manifest.

Please ask to Google review again your app.

May this be useful: https://stackoverflow.com/questions/71473553/action-requested-declare-your-ad-id-permission

**Comment by trash-max** [comment] 2023-10-12 14:14
@gumaciel, the problem is that it is impossible to test the application. Commercial ads are loaded into the test device.

A simple example:
if I make variable

```
const TEST_DEVICES: Array = [
	"4298284AABF842288E8E00793EA7C97E",
	"8C31A0A5C8DFCE5ED3B2DF201B46BC23",
	]

```

and add it on initialization stage:

`request_configuration.test_device_ids.append(TEST_DEVICES)`
or
`request_configuration.test_device_ids.append = TEST_DEVICES`

after app run function in MobileAds.gd returning error on this line:
```
#test_device_ids needs to be passed separarely because Dictionary can't serialize Arrays 
_plugin.set_request_configuration(request_configuration.convert_to_dictionary(), request_configuration.test_device_ids)
```

Error message from logcat:
`E godot   : USER SCRIPT ERROR: Invalid set index 'test_device_ids' (on base: 'RefCounted (RequestConfiguration)') with value of type 'Array'.`

And dictionary with test_device_ids stay emtpy.

**Comment by gumaciel** [comment] 2023-10-13 11:21
Hi @trash-max the problem is because TEST_DEVICES must be a Array[String]

just like this:

```gdscript
const TEST_DEVICES: Array[String] = [
	"4298284AABF842288E8E00793EA7C900",
	"8C31A0A5C8DFCE5ED3B2DF201B46BC99",
	]
```

**Comment by trash-max** [comment] 2023-10-13 13:53
Its worked for testing.
`I Ads     : This request is sent from a test device.`
Thanks.

A little later I will try to send it to Playmarket

**Closed** 2023-10-13 15:34 UTC
Labels: bug
