### ISSUE TITLE
[BUG][BLOCKER] SDK 31/32 + AdMob cause an error

### ISSUE THREAD

**Issue by SnailRabbids** [Poing-Studios/godot-admob-android#130] opened 2022-08-19 18:03 UTC
**Describe the bug**
Android export for SDK 31 and 32 cause an error because of AdMob plugin. Error was found while testing by Play team (see steps).

**To Reproduce**

export with Godot 3.5 and SDK 31 or 32 and enabled AdMob -> upload to Play console -> wait for testing -> in test results is next Stability error: 

```
FATAL EXCEPTION: pool-3-thread-1
Process: com.snailcompanyteam.deutch, PID: 21624
java.lang.IllegalArgumentException: com.snailcompanyteam.deutch: Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.
Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles.
	at android.app.PendingIntent.checkFlags(PendingIntent.java:375)
	at android.app.PendingIntent.getBroadcastAsUser(PendingIntent.java:645)
	at android.app.PendingIntent.getBroadcast(PendingIntent.java:632)
	at androidx.work.impl.utils.ForceStopRunnable.getPendingIntent(ForceStopRunnable.java:174)
	at androidx.work.impl.utils.ForceStopRunnable.isForceStopped(ForceStopRunnable.java:108)
	at androidx.work.impl.utils.ForceStopRunnable.run(ForceStopRunnable.java:86)
	at androidx.work.impl.utils.SerialExecutor$Task.run(SerialExecutor.java:75)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:920)
```

**Expected behavior**
Found this fix: https://www.bswen.com/2022/06/how-to-solve-pendingintent-error.html

There are no error w/o AdMob plugin. and no errors with AdMob plugin and SDK version 30.
As I see, error is caused of changes in SDK 31 and 32, but I cannot find this ( https://www.bswen.com/2022/06/how-to-solve-pendingintent-error.html ) in code, so need some help :(

**Screenshots**
pass

**Smartphone (please complete the following information):**
 - Device: Pixel 6
 - OS: Android 12
 - Godot 3.5

**Additional context**
I don't think it's a good idea to release a new app version with this error.
Same error appears when exporting with Godot 3.4.5 and SDK 31.

**Comment by nathanfranke** [comment] 2022-08-19 19:26
Likely duplicate of https://github.com/Poing-Studios/godot-admob-android/issues/126

**Comment by gumaciel** [comment] 2022-08-19 23:25
Closing since it's similar to #126

**Closed by gumaciel** 2022-08-19 23:25 UTC
Labels: bug
