### ISSUE TITLE
UMP - When user choose no consent, reward ads will not show and there is no error signal return

### ISSUE THREAD

**Issue by kyoz** [Poing-Studios/godot-admob-android#173] opened 2023-06-20 12:36 UTC
### Godot version

3.5.2

### Plugin version

v2.1.4

### Phone information

Samsung Galaxy Note 10+

### Issue description

Normally when user choose no consent. There will be no ads (especially when testing).

So that when we try to show ads. In my case is reward ads. It will cause error and throw `on_rewarded_ad_failed_to_show`

This is working correctly on iOS but not on Android. I have tested on a few phones of mine.

Still need testing and confirm.

### Steps to reproduce

When open game, click "Manage options" -> "Confirm choices".

Then try to show reward ad.

**Comment by gumaciel** [comment] 2023-06-20 23:28
Thank you for opening this Issue, we will investigate

**Comment by gumaciel** [comment] 2023-08-15 00:12
@kyoz Sorry, I can't be able to reproduce it, can you tell with me details the step to reproduce?

The Ad was been loaded before you Do Not Consent?

Or you did do this?
1. Click on Do Not Consent on UMP
2. Successfully Loads the Consent
3. Try to click to Show the Ad and gets the bug.

I just was able to get "failed_to_load error_code = 3" but it's normal

**Comment by kyoz** [comment] 2023-08-15 10:23
@gumaciel I'll tested it again, it's seem it maybe something in GG backend not in our parts.

**Comment by gumaciel** [comment] 2023-08-24 12:25
Closing because cannot reproduce.

If still happens you can re-open the Issue.

---

By the way, we just released the new version of AdMob Plugin which brings Mediation, if you want to test it's here:

**Important Note: This is a BREAKING CHANGE. Please only update to this version if absolutely necessary, as it will require extensive code rewriting. We recommend using version v2.Y.Z if possible.**

https://github.com/Poing-Studios/godot-admob-plugin/releases/tag/v3.0.0
https://github.com/Poing-Studios/godot-admob-android/releases/tag/v3.0.0 
https://github.com/Poing-Studios/godot-admob-ios/releases/tag/v3.0.0

**Closed by gumaciel** 2023-08-24 12:25 UTC
Labels: bug
